name: SL Keep Alive Bot

on:
  schedule:
    # Se ejecuta cada 15 minutos, las 24 horas, los 7 días
    - cron: '*/15 * * * *'
  workflow_dispatch: # Esto permite que tú lo actives manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script de despertar
        run: python wake_up.py
